import {ensureDb,query} from './db';
const split=(x:any)=>String(x||'').split('|').filter(Boolean);
const riskSelect=`SELECT r.*,o.name opened_by_name,a.name assigned_to_name,COALESCE((SELECT GROUP_CONCAT(t.content,'|') FROM risk_tags x JOIN tags t ON t.id=x.tag_id WHERE x.risk_id=r.id),'') tags,COALESCE((SELECT GROUP_CONCAT(objective,'|') FROM risk_threats x WHERE x.risk_id=r.id),'') threat_objectives,COALESCE((SELECT GROUP_CONCAT(i.code,'|') FROM risk_incident_links l JOIN incidents i ON i.id=l.incident_id WHERE l.risk_id=r.id),'') incident_associations,(SELECT COUNT(*) FROM comments c WHERE c.entity_type='risk' AND c.entity_id=r.id) comment_count FROM risks r JOIN users o ON o.id=r.opened_by LEFT JOIN users a ON a.id=r.assigned_to`;
const incidentSelect=`SELECT i.*,o.name opened_by_name,a.name assigned_to_name,COALESCE((SELECT GROUP_CONCAT(t.content,'|') FROM incident_tags x JOIN tags t ON t.id=x.tag_id WHERE x.incident_id=i.id),'') tags,COALESCE((SELECT GROUP_CONCAT(objective,'|') FROM incident_threats x WHERE x.incident_id=i.id),'') threat_objectives,COALESCE((SELECT GROUP_CONCAT(r.code,'|') FROM risk_incident_links l JOIN risks r ON r.id=l.risk_id WHERE l.incident_id=i.id),'') risk_associations,(SELECT COUNT(*) FROM comments c WHERE c.entity_type='incident' AND c.entity_id=i.id) comment_count FROM incidents i JOIN users o ON o.id=i.opened_by LEFT JOIN users a ON a.id=i.assigned_to`;
export async function risks(org='org_acme'){await ensureDb();const rows=await query<any>(`${riskSelect} WHERE r.org_id=? ORDER BY r.id DESC`,[org]);return rows.map((r:any)=>({...r,tags:split(r.tags),threat_objectives:split(r.threat_objectives),incident_associations:split(r.incident_associations)}))}
export async function incidents(org='org_acme'){await ensureDb();const rows=await query<any>(`${incidentSelect} WHERE i.org_id=? ORDER BY i.detected_date DESC`,[org]);return rows.map((r:any)=>({...r,tags:split(r.tags),threat_objectives:split(r.threat_objectives),risk_associations:split(r.risk_associations)}))}
export async function comments(org:string,type:string,id:number){return query<any>("SELECT c.*,u.name user_name,u.initials FROM comments c JOIN users u ON u.id=c.user_id WHERE c.org_id=? AND c.entity_type=? AND c.entity_id=? ORDER BY c.created_at",[org,type,id])}
export async function replaceTags(org:string,type:'risk'|'incident',id:number,tags:string[]){const table=type==='risk'?'risk_tags':'incident_tags',col=type==='risk'?'risk_id':'incident_id';const {run}=await import('./db');await run(`DELETE FROM ${table} WHERE ${col}=?`,[id]);for(const raw of tags){const v=raw.trim();if(!v)continue;await run('INSERT OR IGNORE INTO tags(org_id,content) VALUES(?,?)',[org,v]);const x=await query<any>('SELECT id FROM tags WHERE org_id=? AND content=?',[org,v]);await run(`INSERT OR IGNORE INTO ${table}(${col},tag_id) VALUES(?,?)`,[id,Number(x[0].id)])}}
export async function replaceThreats(type:'risk'|'incident',id:number,items:string[]){const table=type==='risk'?'risk_threats':'incident_threats',col=type==='risk'?'risk_id':'incident_id';const {run}=await import('./db');await run(`DELETE FROM ${table} WHERE ${col}=?`,[id]);for(const v of items)await run(`INSERT OR IGNORE INTO ${table}(${col},objective) VALUES(?,?)`,[id,v])}
export function csv(rows:any[],cols:string[]){const e=(v:any)=>{const s=Array.isArray(v)?v.join('; '):String(v??'');return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s};return [cols.join(','),...rows.map(r=>cols.map(c=>e(r[c])).join(','))].join('\n')}
