export const SCHEMA = `
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,name TEXT NOT NULL,short_name TEXT NOT NULL,tags_json TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,org_id TEXT NOT NULL,email TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL,initials TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS threats(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,objective TEXT NOT NULL,likelihood TEXT NOT NULL,impact TEXT NOT NULL,rationale TEXT NOT NULL,draft_likelihood TEXT,draft_impact TEXT,draft_rationale TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(org_id,objective));
CREATE TABLE IF NOT EXISTS risks(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,code TEXT UNIQUE,status TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,opened_by TEXT NOT NULL,assigned_to TEXT,likelihood TEXT,impact TEXT,urgency TEXT,initial_urgency TEXT,likelihood_reasoning TEXT,impact_reasoning TEXT,source TEXT,type TEXT,remediation_task TEXT,discovered_date TEXT NOT NULL,due_date TEXT,expected_date TEXT,closed_date TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS incidents(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,code TEXT UNIQUE,status TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,opened_by TEXT NOT NULL,assigned_to TEXT,severity TEXT,severity_reasoning TEXT,source TEXT,occurred_date TEXT,detected_date TEXT NOT NULL,responded_date TEXT,contained_date TEXT,closed_date TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tags(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,content TEXT NOT NULL,UNIQUE(org_id,content));
CREATE TABLE IF NOT EXISTS risk_tags(risk_id INTEGER NOT NULL,tag_id INTEGER NOT NULL,PRIMARY KEY(risk_id,tag_id));
CREATE TABLE IF NOT EXISTS incident_tags(incident_id INTEGER NOT NULL,tag_id INTEGER NOT NULL,PRIMARY KEY(incident_id,tag_id));
CREATE TABLE IF NOT EXISTS risk_threats(risk_id INTEGER NOT NULL,objective TEXT NOT NULL,PRIMARY KEY(risk_id,objective));
CREATE TABLE IF NOT EXISTS incident_threats(incident_id INTEGER NOT NULL,objective TEXT NOT NULL,PRIMARY KEY(incident_id,objective));
CREATE TABLE IF NOT EXISTS risk_incident_links(risk_id INTEGER NOT NULL,incident_id INTEGER NOT NULL,PRIMARY KEY(risk_id,incident_id));
CREATE TABLE IF NOT EXISTS comments(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id INTEGER NOT NULL,user_id TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id INTEGER NOT NULL,provider TEXT NOT NULL,external_id TEXT NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS documents(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,slug TEXT NOT NULL,acronym TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,version TEXT NOT NULL,state TEXT NOT NULL,content TEXT NOT NULL,ai_sections TEXT NOT NULL,approved_at TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(org_id,slug));
CREATE TABLE IF NOT EXISTS document_versions(id INTEGER PRIMARY KEY AUTOINCREMENT,document_id INTEGER NOT NULL,version TEXT NOT NULL,content TEXT NOT NULL,change_summary TEXT NOT NULL,status TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,approved_by TEXT,approved_at TEXT);
CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,type TEXT NOT NULL,title TEXT NOT NULL,period_start TEXT NOT NULL,period_end TEXT NOT NULL,executive_summary TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS integrations(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,provider TEXT NOT NULL,category TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,auto_score INTEGER NOT NULL DEFAULT 0,config_json TEXT NOT NULL DEFAULT '{}',last_status TEXT,UNIQUE(org_id,provider));
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,user_id TEXT,entity_type TEXT,entity_id INTEGER,message TEXT NOT NULL,is_read INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS saved_views(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,module TEXT NOT NULL,name TEXT NOT NULL,filters_json TEXT NOT NULL,UNIQUE(user_id,module,name));
CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,org_id TEXT NOT NULL,user_id TEXT NOT NULL,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,details_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS portfolio_stats(org_id TEXT PRIMARY KEY,risk_sla_percent INTEGER NOT NULL,incidents_open INTEGER NOT NULL,sev1 INTEGER NOT NULL,sev2 INTEGER NOT NULL,sev3 INTEGER NOT NULL,compliance_state TEXT NOT NULL);
`;
export const SEED = [
`INSERT OR IGNORE INTO organizations VALUES ('org_acme','Acme Inc','ACME','["SaaS","Sector: Tech","Customer-facing"]'),('org_kestrel','Kestrel Dynamics','KD','["Aerospace","Sector: Defense"]'),('org_tabula','Tabula Retail Group','TR','["Retail","Payments"]'),('org_northgate','Northgate Utilities','NU','["Utilities","Sector: OT","Critical Infrastructure"]');`,
`INSERT OR IGNORE INTO users VALUES ('u_admin','org_acme','tommy@acme.example','Tommy McCormick','Admin','TM',1),('u_editor','org_acme','carol@acme.example','Carol Wu','Editor','CW',1),('u_viewer','org_acme','jane@acme.example','Jane Doe','Viewer','JD',1),('u_risk','org_acme','priya@acme.example','Priya Rao','Risk Editor','PR',1),('u_incident','org_acme','alex@acme.example','Alex Morgan','Incident Editor','AM',1);`,
`INSERT OR IGNORE INTO threats(org_id,objective,likelihood,impact,rationale) VALUES ('org_acme','Extortion','Imminent','High','Ransomware and extortion remain the top driver for a SaaS business with internet-facing production systems.'),('org_acme','Data Disclosure','Possible','High','Customer and employee data create meaningful disclosure impact even when likelihood is moderated by controls.'),('org_acme','Fraud','Probable','High','Payment, payroll, and executive impersonation scenarios make fraud a persistent business risk.'),('org_acme','Sabotage','Unlikely','Severe','Disruption would be severe, but there is limited intelligence indicating targeted destructive intent.'),('org_acme','Resource Hijacking','Probable','Medium','Elastic cloud resources make cryptojacking and resource abuse plausible but generally recoverable.'),('org_acme','Customer Targeting','Unlikely','High','The platform has privileged customer relationships, but strong tenant isolation reduces likelihood.');`,
`INSERT OR IGNORE INTO risks(id,org_id,code,status,title,description,opened_by,assigned_to,likelihood,impact,urgency,initial_urgency,source,type,remediation_task,discovered_date,due_date,expected_date,closed_date) VALUES
(1,'org_acme','RSK-00234','Remediation','Log4j on public customer portal','External scan found a vulnerable Java component on an internet-facing customer service endpoint.','u_admin','u_editor','Probable','High','Critical','Critical','Bug Bounty','Vulnerability','Upgrade dependency and validate transitive packages.','2026-04-11','2026-04-25','2026-04-22',NULL),
(2,'org_acme','RSK-00236','Remediation','Insufficient input validation in payout API','Build-time testing identified a request validation gap in payout instructions.','u_admin','u_editor','Probable','High','Critical','Critical','Bug Bounty','Code','Add schema validation, negative tests, and abuse-rate monitoring.','2026-04-18','2026-05-02','2026-04-29',NULL),
(3,'org_acme','RSK-00238','Remediation','Call center susceptible to MFA fatigue','A red-team exercise showed help-desk workflows can be abused to trigger repeated authentication prompts.','u_admin','u_risk','Probable','High','Critical','Critical','Red Team','Control Deficiency','Require phishing-resistant recovery for privileged accounts.','2026-05-03','2026-05-17','2026-05-15',NULL),
(4,'org_acme','RSK-00302','Remediation','Weak travel policy for privileged admin devices','Policy permits routine travel with primary privileged laptops without hardened travel profiles.','u_risk','u_risk','Possible','High','High','Critical','Internal Audit','Policy','Adopt hardened travel profiles and loaner devices.','2026-05-25','2026-06-08','2026-06-06',NULL),
(5,'org_acme','RSK-00315','New','Cloud logging bucket allows overly broad read','Wiz identified a logging bucket with a broad IAM binding. No public access is present.','u_admin','u_editor','Possible','Medium','Medium','High','Wiz','Configuration','Tighten IAM to the logging service and response group.','2026-06-12','2026-07-12','2026-07-08',NULL),
(6,'org_acme','RSK-00322','Closed','npm package vulnerability limited to internal build worker','Critical CVE is limited to an isolated build worker with no inbound network path.','u_admin','u_editor','Unlikely','Medium','Low','Critical','Dependabot','Code','Upgrade dependency during normal maintenance.','2026-06-18','2026-07-18','2026-07-10','2026-07-09'),
(7,'org_acme','RSK-00331','Closure Proposed','Public admin panel missing IP allowlist','Attack-surface monitoring found an administrative interface exposed to the public internet. MFA is enforced.','u_admin','u_editor','Probable','High','Critical','Medium','WatchTowr','Configuration','Restrict access through the corporate access proxy.','2026-06-29','2026-07-13','2026-07-10',NULL),
(8,'org_acme','RSK-00348','Urgency Proposed','Vendor SSO does not require phishing-resistant MFA','Strategic SaaS provider has not enabled phishing-resistant authentication for support access.','u_editor','u_risk','Possible','High','High','High','Third-Party Review','Third-party','Require hardware-backed MFA for privileged support accounts.','2026-07-07','2026-08-06','2026-08-01',NULL),
(9,'org_acme','RSK-00357','Closed','Stale endpoint security agent on retired lab device','Endpoint agent stopped reporting on a device scheduled for disposal.','u_editor','u_editor','Remote','Low','Info','Medium','EDR','Control Deficiency','Retire and wipe the device.','2026-07-11','2026-08-10','2026-07-20','2026-07-19'),
(10,'org_acme','RSK-00370','New','Backup restore evidence incomplete','Audit found one application team has not attached evidence from the latest restore test.','u_editor','u_editor','Possible','High','High','Medium','Internal Audit','Procedural','Complete a restore test and retain evidence.','2026-07-22','2026-08-21','2026-08-15',NULL),
(11,'org_acme','RSK-00381','Remediation','Container registry permits anonymous pull','A production image registry allows unauthenticated pull access for several repositories.','u_admin','u_editor','Probable','Medium','High','High','CSPM','Configuration','Disable anonymous pull and rotate embedded credentials.','2026-08-01','2026-08-15','2026-08-14',NULL),
(12,'org_acme','RSK-00395','New','VPN appliance zero-day relevant to our estate','Threat intelligence identified active exploitation of the same remote-access appliance family used by Acme.','u_admin','u_risk','Probable','High','Critical','Critical','Adversarial Intelligence','Vulnerability','Patch immediately, rotate credentials, and review logs.','2026-08-13','2026-08-15','2026-08-14',NULL);`,
`INSERT OR IGNORE INTO incidents(id,org_id,code,status,title,description,opened_by,assigned_to,severity,severity_reasoning,source,occurred_date,detected_date,responded_date,contained_date,closed_date) VALUES
(1,'org_acme','INC-00317','In Progress','Credential stuffing against admin SSO','Distributed credential-stuffing campaign is hitting the admin SSO endpoint; response is in progress.','u_admin','u_editor','SEV-2','Targeted malicious activity produced limited successful compromise of privileged service accounts.','CrowdStrike','2026-08-02T06:10:00Z','2026-08-02T06:17:00Z','2026-08-02T06:32:00Z',NULL,NULL),
(2,'org_acme','INC-00446','Closed','Lockbit ransomware infection','Ransomware deployed in the Austin office through a compromised endpoint. Region isolated and restored.','u_incident','u_incident','SEV-1','Widespread operational impact and extortion required executive and legal escalation.','MDR','2026-01-16T02:00:00Z','2026-01-16T02:09:00Z','2026-01-16T02:17:00Z','2026-01-16T03:11:00Z','2026-01-19T18:00:00Z'),
(3,'org_acme','INC-00921','Closed','Misdirected payroll export','Payroll export was emailed to an unintended internal distribution list and recalled.','u_editor','u_incident','SEV-3','Bounded internal data disclosure with rapid containment.','Employee Reported','2026-03-21T14:00:00Z','2026-03-21T14:12:00Z','2026-03-21T14:18:00Z','2026-03-21T14:35:00Z','2026-03-22T16:00:00Z'),
(4,'org_acme','INC-01042','Review','Executive ACH fraud attempt','Finance intercepted a spoofed executive payment request before funds moved.','u_admin','u_incident','SEV-3','Targeted fraud attempt required investigation but caused no financial loss.','Employee Reported','2026-05-08T10:00:00Z','2026-05-08T10:11:00Z','2026-05-08T10:20:00Z','2026-05-08T10:50:00Z',NULL),
(5,'org_acme','INC-01211','Closed','Cryptominer on development node','EDR isolated a cryptominer running on an ephemeral development node.','u_incident','u_incident','SEV-4','Limited resource hijacking with no production access.','CrowdStrike','2026-06-04T03:20:00Z','2026-06-04T03:25:00Z','2026-06-04T03:30:00Z','2026-06-04T03:44:00Z','2026-06-04T18:00:00Z'),
(6,'org_acme','INC-01305','Review','Compromised supplier package detected','Build pipeline detected a suspicious dependency update and blocked promotion.','u_admin','u_editor','SEV-3','Supply-chain compromise reached development but not production.','SCA','2026-06-29T18:30:00Z','2026-06-29T18:38:00Z','2026-06-29T18:45:00Z','2026-06-29T19:12:00Z',NULL),
(7,'org_acme','INC-01392','Closed','Phishing click with no credential entry','Employee clicked a phishing URL but browser isolation prevented credential submission.','u_editor','u_incident','SEV-4','User interaction occurred but controls prevented compromise.','Email Security','2026-07-10T12:11:00Z','2026-07-10T12:13:00Z','2026-07-10T12:18:00Z','2026-07-10T12:22:00Z','2026-07-10T19:00:00Z'),
(8,'org_acme','INC-01428','In Progress','Suspicious OAuth consent grant','Identity monitoring detected an anomalous OAuth consent grant to a third-party application.','u_admin','u_editor','SEV-3','Potential data access exists pending application and token review.','Identity','2026-07-24T09:05:00Z','2026-07-24T09:08:00Z','2026-07-24T09:20:00Z',NULL,NULL),
(9,'org_acme','INC-01490','Closed','Red-team persistence simulation','Authorized red team established persistence to validate detection engineering.','u_incident','u_incident','SEV-5','Expected control-test activity with no real adversary.','Red Team','2026-08-01T15:00:00Z','2026-08-01T15:10:00Z','2026-08-01T15:15:00Z','2026-08-01T15:30:00Z','2026-08-01T17:00:00Z'),
(10,'org_acme','INC-01531','New','Unsanctioned AI upload of customer snippet','DLP flagged a customer-data snippet uploaded to an unapproved generative AI service.','u_admin','u_incident','SEV-3','Customer data left an approved boundary; scope and retention are under review.','DLP','2026-08-13T16:30:00Z','2026-08-13T16:31:00Z',NULL,NULL,NULL);`,
`INSERT OR IGNORE INTO risk_incident_links VALUES (3,1),(4,2),(10,2),(8,4);`,
`INSERT OR IGNORE INTO tags(org_id,content) VALUES ('org_acme','Internet-facing'),('org_acme','Customer data'),('org_acme','Identity'),('org_acme','Audit'),('org_acme','Third party'),('org_acme','Production'); INSERT OR IGNORE INTO risk_tags VALUES (1,1),(1,6),(3,3),(8,5),(10,4),(12,1); INSERT OR IGNORE INTO incident_tags VALUES (1,3),(2,6),(4,3),(10,2);`,
`INSERT OR IGNORE INTO risk_threats VALUES (1,'Extortion'),(1,'Data Disclosure'),(3,'Fraud'),(7,'Data Disclosure'),(8,'Data Disclosure'),(12,'Extortion'); INSERT OR IGNORE INTO incident_threats VALUES (1,'Fraud'),(1,'Data Disclosure'),(2,'Extortion'),(4,'Fraud'),(5,'Resource Hijacking'),(10,'Data Disclosure');`,
`INSERT OR IGNORE INTO comments(org_id,entity_type,entity_id,user_id,body) VALUES ('org_acme','risk',12,'u_risk','Appliance inventory confirms one externally reachable instance. Patch window approved.'),('org_acme','incident',1,'u_editor','Two service accounts reset; reviewing successful sessions and token issuance.');`,
`INSERT OR IGNORE INTO documents(id,org_id,slug,acronym,title,description,version,state,content,ai_sections,approved_at) VALUES (1,'org_acme','charter','CHTR','Cybersecurity Charter','Program mandate, oversight and accountability.','2.0','approved','Purpose\nEstablish accountability, governance and security decision rights.\n\nOversight\nThe executive sponsor reviews material risk and incident decisions.','None','2026-01-10'),(2,'org_acme','risk-management','RAMP','Risk Assessment & Management Procedure','Governed risk scoring, treatment and closure process.','2.4','approved','Intake\nNormalize findings from tooling, audits, employee reports and intelligence.\n\nScoring\nAssign likelihood and impact with written reasoning; derive urgency.\n\nTreatment\nTrack remediation against due dates and expected dates.','Likelihood and impact suggestion; urgency derivation.','2026-06-18'),(3,'org_acme','incident-response','CIRP','Cybersecurity Incident Response Procedure','Severity rubric, response milestones, referral to risk.','3.1','approved','Triage\nClassify incidents from SEV-1 through SEV-5.\n\nRespond\nTrack detected, responded and contained milestones.\n\nLearn\nCreate or link risk records for systemic lessons learned.','Severity suggestion and executive summary.','2026-05-22'),(4,'org_acme','security-program','CISP','Cybersecurity Information Security Program','Program control responsibilities and operating expectations.','1.8','approved','Program\nOperate the threat, risk, incident and compliance lifecycle as one governed system of record.','Control narrative assistance.','2026-07-02');`,
`INSERT OR IGNORE INTO reports(id,org_id,type,title,period_start,period_end,executive_summary,created_by,created_at) VALUES (1,'org_acme','Board','Q2 2026 Board Deck','2026-04-01','2026-06-30','Extortion, Fraud, and Data Disclosure remain program priorities. Remediation velocity improved after the May backlog spike.','u_admin','2026-07-02T10:00:00Z'),(2,'org_acme','CyberGov','Q1 2026 CyberGov Report','2026-01-01','2026-03-31','A SEV-1 ransomware incident drove additional resilience actions and new risk-register entries.','u_admin','2026-04-04T10:00:00Z');`,
`INSERT OR IGNORE INTO integrations(org_id,provider,category,enabled,auto_score,config_json,last_status) VALUES ('org_acme','Wiz','Risk',1,1,'{}','Healthy'),('org_acme','CrowdStrike','Incident',1,0,'{}','Healthy'),('org_acme','HackerOne','Risk',1,1,'{}','Healthy'),('org_acme','WatchTowr','Risk',1,1,'{}','Healthy'),('org_acme','Jira','Ticketing',1,0,'{}','Connected'),('org_acme','ServiceNow','Ticketing',1,0,'{}','Connected'),('org_acme','Linear','Ticketing',0,0,'{}','Not configured'),('org_acme','Slack','Notification',0,0,'{}','Not configured'),('org_acme','Teams','Notification',0,0,'{}','Not configured');`,
`INSERT OR IGNORE INTO notifications(id,org_id,user_id,entity_type,entity_id,message,is_read,created_at) VALUES (1,'org_acme','u_admin','risk',12,'RSK-00395 is a new Critical risk from threat intelligence.',0,'2026-08-13T18:00:00Z'),(2,'org_acme','u_editor','incident',1,'INC-00317 remains In Progress and is assigned to you.',0,'2026-08-14T07:30:00Z'),(3,'org_acme',NULL,'incident',10,'INC-01531 is a new SEV-3 Data Disclosure incident.',1,'2026-08-13T17:00:00Z');`,
`INSERT OR IGNORE INTO portfolio_stats VALUES ('org_acme',118,3,0,1,2,'Active'),('org_kestrel',62,4,0,0,1,'Active'),('org_tabula',340,64,4,7,18,'In review'),('org_northgate',186,19,2,4,8,'Active');`
];
